"""empty message

Revision ID: 52c7468fa21
Revises: 25eced811a3
Create Date: 2014-11-04 08:37:21.691873

"""

# revision identifiers, used by Alembic.
revision = '52c7468fa21'
down_revision = '25eced811a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
